version: "3"
services:
  pgdb:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=world
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./world.sql:/docker-entrypoint-initdb.d/00_world.sql
    networks:
      - pg-net
  pgadmin:
    image: dpage/pgadmin4:snapshot
    ports:
      - "9000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - ./entrypoint-mod.sh:/entrypoint-mod.sh
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpassfile:/pgadmin4/pgpassfile
    networks:
    - pg-net
    entrypoint: /entrypoint-mod.sh
networks:
  pg-net:
volumes:
  pg-data:
